<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Api</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
        <PackageReference Include="NuGet.Packaging" Version="6.13.0" />
        <PackageReference Include="NuGet.Protocol" Version="6.13.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Anexcs.Distro.Application\Anexcs.Distro.Application.csproj" />
      <ProjectReference Include="..\Anexcs.Distro.Infrastructure\Anexcs.Distro.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Contracts\Central\" />
      <Folder Include="Controllers\Central\" />
      <Folder Include="Extensions\" />
      <Folder Include="Middlewares\" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
